export const types = {
  ADD_PIZZA_TO_CART: "CART: ADD_PIZZA_TO_CART",
  CART_CLEAR: "CART: CART_CLEAR",
  REMOVE_FROM_CART: "CART: REMOVE_FROM_CART",
  MINUS_ONE_PIZZA: "CART: MINUS_ONE_PIZZA",
  SET_CATEGORY: "FILTER: SET_CATEGORY",
  SET_SORT_BY: "FILTER: SET_SORT_BY",
  FETCH_PIZZA: "PIZZA: FETCH_PIZZA",
}
